### PR TITLE
Add interpolation

### PR DESCRIPTION
**Pull request by nzlz**
Improved grippers general behavior
 - Added a Reset() function to handle simulation reset properly.
 - Added interpolation. Previously new goals where executed instantly. 

Note that interpolation's duration is calculated using the `MaxVelocity` variable available in the header file:
```cpp
    /// \brief Max. joint speed (rad/s). Finger is 125mm and tip speed is 110mm/s.
    private: const double MaxVelocity = 0.88;
```
Maybe we should add gripping speed to the URDF file? Or provide a service call to tune it?

Also to provide more accurate visual speed we should not rely on the connection update event to push the next interpolation pose to gazebo. Instead a 1ms (matching interpolation time increment) wall timer would be better (I think).

**Note**: The blue point is a non colliding object, only visual.
gripping

---
We have some physics problems as you can see in the image below. I'll try to improve it and make a new PR. ( the robot is shaking because im executing new actions continuously, + using the old driver. This won't happen in a real simulation scenario)
grip_fail

### CODE REVIEW

**Comment by rkojcev** [comment]
looks really good @nzlz too bad about the physics

**Comment by nzlz** [comment]
Ping @ahcorde

**Comment by alesolano** [comment]
Having this error when building ros2_mara_ws (see [MARA repo](https://github.com/AcutronicRobotics/MARA#compile-the-ros-20-workspace)) using your fork as `robotiq_modular_gripper`

`/home/developer/ros2_mara_ws/src/robotiq_modular_gripper/robotiq_gripper_gazebo_plugins/src/spline.cpp:1:10: fatal error: mara_gazebo_plugins/spline.hpp: No such file or directory
 #include "mara_gazebo_plugins/spline.hpp"
`

I'm having a look

**Comment by nzlz** [comment]
Thanks for testing @alesolano ,
Fixed, can you try again? (working for me in this particular gripper)

How to test:
```bash
ros2 launch robotiq_gazebo robotiq_85.launch.py

ros2 service call /robotiq_85_gripper/goal hrim_actuator_gripper_srvs/ControlFinger "{goal_linearposition: 0.7}"
```
It would be nice if you could test that works fine with 3 grippers and also a full MARA.

**Note**: Topic name is not hrim_ in 3 grippers yet since this is an old PR, but will be once its merged with master.

**Comment by alesolano** [comment]
Working nice. This is the result that I get:

interpol

> Note: Topic name is not hrim_ in 3 grippers yet since this is an old PR, but will be once its merged with master.

is there a way to test this before merging?

If there's no problem with that, then LGTM

**Comment by nzlz** [comment]
> is there a way to test this before merging?

Sure the same way you tested this but with the other components. I'll do it if @ahcorde thinks its necessary, so far S140 and S85 work fine.

**Comment by rkojcev** [comment]
Let's merge this. It has been tested and it works fine.

**Review by LanderU — APPROVED** [review]
LGTM!

**Comment by ahcorde** [comment]
I don't really like the idea of adding splice.cpp in the code.

**Comment by rkojcev** [comment]
We already use spline in the MARA this just simplifies things in simulation without dealing with PIDs and not having the ros control ported in ros2 and gazebo. Once ros control is ported we can think of removing splines and using directly that. 

In this moment we do not have other alternatives regarding controlling smooth trajectories of the gripper in simulation. 

I suggest we add this so at least we can approximately replicate the behavior of the gripper in simulation.

**Pull request merged**
